// GENERATED by scripts/media/competition-logos.mjs: approved competition logos (same-origin cached copies).
// Identity: exact ESPN league id from soccer_competition_external_ids; provenance in soccer_entity_media
// (rights_status owner_approved_identification: NOT free-licensed). Do not edit by hand.
export const COMPETITION_MEDIA = {
  "uefa-champions-league": {
    "url": "/api/soccer/media/638ba01ea2dc0679766a8a1c4152756108cadb6763b2f016c8ca5f5c9784ebc7",
    "url_dark": "/api/soccer/media/a603dfbec53840a728229e2c2c1848e77c096e5018256fe260fa7dafd559deca",
    "attribution": "UEFA Champions League logo. Image: ESPN",
    "basis": "owner_approved_identification"
  },
  "premier-league": {
    "url": "/api/soccer/media/42e2fdced44ff542fa734409667c733841a7bcb903b526c85d12aac78aff2464",
    "url_dark": "/api/soccer/media/3fbb077c9331046d0dc96c0bbcc12e3795bdbd9b43a6bbe3a18ab6b6aedc47bf",
    "attribution": "Premier League logo. Image: ESPN",
    "basis": "owner_approved_identification"
  },
  "bundesliga": {
    "url": "/api/soccer/media/463b74682c9030631d8fc19a1535875496009a8f296775323127e2a2365094d0",
    "url_dark": "/api/soccer/media/a34af0a55df761a807dc43d1afff86ffa3d3a7fabf4d952c1364562973c5cff3",
    "attribution": "Bundesliga logo. Image: ESPN",
    "basis": "owner_approved_identification"
  },
  "uefa-nations-league": {
    "url": "/api/soccer/media/105291b28134e6b377795fd80d0d5c8c561f02257bfb1a5b243b87df0ebe6b19",
    "url_dark": "/api/soccer/media/105291b28134e6b377795fd80d0d5c8c561f02257bfb1a5b243b87df0ebe6b19",
    "attribution": "UEFA Nations League logo. Image: ESPN",
    "basis": "owner_approved_identification"
  },
  "mls": {
    "url": "/api/soccer/media/9e4b7c06391ad3742294dc761e7b951d0bf8603fd2b360370e1299832f602a9e",
    "url_dark": "/api/soccer/media/9e4b7c06391ad3742294dc761e7b951d0bf8603fd2b360370e1299832f602a9e",
    "attribution": "MLS logo. Image: ESPN",
    "basis": "owner_approved_identification"
  }
};
